-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE VIEW user_author_access AS
-- select u.id as user_id, a.id as author_id
-- from "user" u
-- cross join author a;
